import "./globals.css";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { Toaster } from "react-hot-toast";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Toaster position="top-center" reverseOrder={false} />
                <NextAuthProvider>{children}</NextAuthProvider>
            </body>
        </html>
    );
}
